// <auto-generated />
using System;
using FPMG.ExamService.DataAccessLayers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FPMG.ExamService.DataAccessLayers.Migrations
{
    [DbContext(typeof(ExamManagementDBContext))]
    [Migration("20250605104924_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FPMG.ExamService.BussinessObjects.Exams", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamId"));

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SemestersSemesterId")
                        .HasColumnType("int");

                    b.HasKey("ExamId");

                    b.HasIndex("SemestersSemesterId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("FPMG.ExamService.BussinessObjects.Semesters", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SemesterId");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("FPMG.ExamService.BussinessObjects.Submissions", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int?>("ExamsExamId")
                        .HasColumnType("int");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("UploadDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SubmissionId");

                    b.HasIndex("ExamsExamId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("FPMG.ExamService.BussinessObjects.Exams", b =>
                {
                    b.HasOne("FPMG.ExamService.BussinessObjects.Semesters", null)
                        .WithMany("Exam")
                        .HasForeignKey("SemestersSemesterId");
                });

            modelBuilder.Entity("FPMG.ExamService.BussinessObjects.Submissions", b =>
                {
                    b.HasOne("FPMG.ExamService.BussinessObjects.Exams", null)
                        .WithMany("Submissions")
                        .HasForeignKey("ExamsExamId");
                });

            modelBuilder.Entity("FPMG.ExamService.BussinessObjects.Exams", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("FPMG.ExamService.BussinessObjects.Semesters", b =>
                {
                    b.Navigation("Exam");
                });
#pragma warning restore 612, 618
        }
    }
}
