<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FPMG.UserService.BussinessObjects\FPMG.UserService.BussinessObjects.csproj" />
    <ProjectReference Include="..\FPMG.UserService.DataAccessLayers\FPMG.UserService.DataAccessLayers.csproj" />
  </ItemGroup>

</Project>
