// <auto-generated />
using FPMG.UserService.DataAccessLayers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FPMG.UserService.DataAccessLayers.Migrations
{
    [DbContext(typeof(UserManagementDBContext))]
    [Migration("20250605100622_fixUserandRoleTableName")]
    partial class fixUserandRoleTableName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FPMG.UserService.BussinessObjects.Roles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Head"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Examiner"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Lecturer"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "Student"
                        });
                });

            modelBuilder.Entity("FPMG.UserService.BussinessObjects.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "head@fpmg.edu",
                            Password = "123",
                            RoleId = 1,
                            UserName = "head"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "examiner@fpmg.edu",
                            Password = "123",
                            RoleId = 2,
                            UserName = "examiner"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "lecturer1@fpmg.edu",
                            Password = "123",
                            RoleId = 3,
                            UserName = "lecturer1"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "lecturer2@fpmg.edu",
                            Password = "123",
                            RoleId = 3,
                            UserName = "lecturer2"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "student1@fpmg.edu",
                            Password = "123",
                            RoleId = 4,
                            UserName = "student1"
                        },
                        new
                        {
                            UserId = 6,
                            Email = "student2@fpmg.edu",
                            Password = "123",
                            RoleId = 4,
                            UserName = "student2"
                        },
                        new
                        {
                            UserId = 7,
                            Email = "student3@fpmg.edu",
                            Password = "123",
                            RoleId = 4,
                            UserName = "student3"
                        },
                        new
                        {
                            UserId = 8,
                            Email = "student4@fpmg.edu",
                            Password = "123",
                            RoleId = 4,
                            UserName = "student4"
                        },
                        new
                        {
                            UserId = 9,
                            Email = "student5@fpmg.edu",
                            Password = "123",
                            RoleId = 4,
                            UserName = "student5"
                        },
                        new
                        {
                            UserId = 10,
                            Email = "student6@fpmg.edu",
                            Password = "123",
                            RoleId = 4,
                            UserName = "student6"
                        });
                });

            modelBuilder.Entity("FPMG.UserService.BussinessObjects.Users", b =>
                {
                    b.HasOne("FPMG.UserService.BussinessObjects.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FPMG.UserService.BussinessObjects.Roles", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
